### ISSUE TITLE
Graphic debug doesn't start on SAMS 3.9.0 under Win7 Home Premium 64 bit

### ISSUE THREAD

**Issue by techno1st** [Dman95/SASM#100]
I try to compile the predefined examples: FASMHello.asm and GASHello.asm.

In either case, changing the appropriate SAMS Options (FASM or GAS) and compiling for x86 32bit, the code is compiled and executed correctly.

But when i start debug, i see "Debugging Started" but i can't see registers window, memory window and so on.. and i can't perform step by step or stop debug.

The gdb process is in execution and it is terminate only if i close the SASM IDE.

Debug with GAS:
![sasm_debuggas](https://user-images.githubusercontent.com/36201764/42887731-f10a4e40-8aa6-11e8-806f-95b366715b01.png)

Debug with FASM:
![sasm_debugfasm](https://user-images.githubusercontent.com/36201764/42887733-f14e5ae0-8aa6-11e8-858a-30763106905b.png)

**Comment by Dman95** [comment]
Hello!
Can't reproduce. In both cases I have the debugger working.
Try to reinstall the program.
