### ISSUE TITLE
Add support for MASM 16-bit?

### ISSUE THREAD

**Issue by dreamski21** [Dman95/SASM#104]
In our university we use MASM 16-bit, it would be useful if an app like SASM supported it :-)

**Comment by piper4hire** [comment]
It’s finally a nice fall day here. How’s the weather where you are?

-S

**Comment by Dman95** [comment]
16-bit MASM doesn't work with 64-bit operating systems. Also it is not possible to perform debugging of such programs. Instead of this you can use MASM32. Or you can choose MASM assembler in settings and set up build system to work with 16-bit MASM but debugging will not work anyway.
