### ISSUE TITLE
Memory debugging doesn't work in FASM

### ISSUE THREAD

**Issue by jlxip** [Dman95/SASM#105]
When debugging any program, registers work and update fine. However, memory does not work at all (with FASM, it seems to work with NASM).

When selected a variable, it is shown "Wrong variable or address" (see image).

Tested on both GNU/Linux Debian 9.5 (stretch) and Windows 7. Maybe it's just my configuration, I don't know. I would appreciate it if you could test it and see if it works on your machine. Thanks!

![captura de pantalla de 2018-10-08 00-51-44](https://user-images.githubusercontent.com/8456551/46587954-58e25a80-ca94-11e8-915d-89f3f01b4be8.png)

**Comment by Dman95** [comment]
See #92
