### ISSUE TITLE
undefined reference to `get_stdout'

### ISSUE THREAD

**Issue by Antaury2018** [Dman95/SASM#106]
When I try to compile something I get the "undefined reference to `get_stdout' " everytime, no matter the code. Does anyone know how to fix this?

**Comment by Dman95** [comment]
Which OS and version of SASM do you use? Which code are you trying to compile?

**Comment by Antaury2018** [comment]
Windows 10, Sasm v 3.10.0 and the code is:
%include "io.inc"
 
section .text
global CMAIN
CMAIN:                        
    mov eax, 7          
    mov ebx, 8          
    add eax, ebx        
                        
    PRINT_UDEC 4, eax

**Comment by Dman95** [comment]
Thank you! It was really a bug appeared in 3.10.0.
I have fixed it in 3.10.1: [https://github.com/Dman95/SASM/releases/tag/v3.10.1](https://github.com/Dman95/SASM/releases/tag/v3.10.1)
After running new version go to the settings and click on "Reset all" button.
