### ISSUE TITLE
Pressing F5 to debug doesn't work

### ISSUE THREAD

**Issue by zic89** [Dman95/SASM#107]
First Press F5 to Debug and contine to the end, it works fine.
While Pressing F5 to debug again, doesn't work and hotkey is missing
<img width="358" alt="59325a1f-c904-4283-b31b-954fccf29592" src="https://user-images.githubusercontent.com/26269444/46807079-bbd93780-cd9b-11e8-8a22-a6c491a2e0f5.png">
<img width="316" alt="789d21b3-e134-474e-a738-579ff42c8545" src="https://user-images.githubusercontent.com/26269444/46807085-c09deb80-cd9b-11e8-8dee-a8126e2e3699.png">

**Comment by jlxip** [comment]
Can confirm. It happened to me a bunch of times.

**Comment by 5antoro** [comment]
Thank you for the heads up guys

**Comment by Dman95** [comment]
Problem was fixed. Fix will be available soon in the next release.
