### ISSUE TITLE
First Try failed "Unable to start assembler. Check your settings."

### ISSUE THREAD

**Issue by cakebytheoceanLuo** [Dman95/SASM#114]
Hi 
I have a `Ubuntu 18.04 LTS` and just installed our SASM with `qmake` + `make` + `make install`.
It worked and I could start our SASM with `./sasm` with seeing the GUI.
But if I try to compile even with the default code 
```
%include "io.inc"

section .text
global CMAIN
CMAIN:
    ;write your code here
    xor eax, eax
    ret
```

The console of SAMA will always gives me:
```
[10:21:16] Build started...
[10:21:16] Unable to start assembler. Check your settings.
```
Same for the other code, that I try to compile.

My setting is below, if it is necessary to post my other information, just tell me, thanks!
![image](https://user-images.githubusercontent.com/28505034/51025159-9a027300-158b-11e9-8635-48a42c91c0f6.png)

**Comment by lmaonayz** [comment]
What's up my squad 🤙

**Comment by CyberReflect** [comment]
YOLO

**Comment by cakebytheoceanLuo** [comment]
Hi Do you guys have idea to solve the problem?
