### ISSUE TITLE
Hi Do you guys have idea to solve the problem?

### ISSUE THREAD

**Issue by mygithubid1** [Dman95/SASM#120]
Hi Do you guys have idea to solve the problem?

_Originally posted by @cakebytheoceanLuo in https://github.com/Dman95/SASM/issues/114#issuecomment-453464610_

Your sasm config depends on
- nasm (https://www.nasm.us/)
- gcc
Install them and you should be good to go.

**Comment by HUMZZY** [comment]
brother how would i no if im getting hacked my secret keys went missing mac id and sanddisk i need help surureing replaceing my id secrets regaining acces to my funds with out them getting disderbed

________________________________
