### ISSUE TITLE
SASM deletes files during exit

### ISSUE THREAD

**Issue by SP5LMA** [Dman95/SASM#121]
I obtained current version from github, compiled and started the program succesfully.
I started copy from /tmp/SASM without installing it in in system-wide directory as I always test new apps. During exit SASM deletes its directory with all files within. Calls to delete functions are clearly visible with strace. Behavior is repeatable.

App looks promising but honestly I am afraid to use it.

No software should ever delete any files without clear user consent!

**Comment by lberserq** [comment]
AFAIK SASM deletes all files in /tmp/SASM because it stores temporary compilation files there. If you want to install it in a temporary directory, use home directory instead, or use a different name in /tmp

**Comment by awhite200** [comment]
I want to unsubscribe 


Sent from Yahoo Mail for iPhone


On Sunday, January 26, 2020, 4:01 PM, Dmitriy Manushin <notifications@github.com> wrote:


Closed #121.

**Comment by emendblu** [comment]
Request denied!

**Comment by proabbe** [comment]
How do you unsubscribe o.O

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Xanfireblade16** [comment]
Recover your github account. Log in, and continue from there. These fags hijack accounts inorder to boost their "watching" and their "stars"

**Comment by proabbe** [comment]
Alright cool

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by emendblu** [comment]
You don’t unsubscribe. You can double subscribe if you want?
