### ISSUE TITLE
Gives Error while running MASM Program.

### ISSUE THREAD

**Issue by KILLinefficiency** [Dman95/SASM#123]
I have followed the instructions on the SASM Website about setting up MASM. I have successfully installed and set up MASM32 on my machine. I am trying out assembly language and am following Kip Irvine's "Assembly Language for x86 Processors (7th edition)". The book tells that MASM32 is a variant of MASM. The book teaches MASM, while I have installed MASM32 (which the SASM website asked the user to install. Also the book mentioned MASM and MASM32 to be two different things/assemblers). Anyhow, on running, I am getting this error:

![sasm_error](https://user-images.githubusercontent.com/43932047/57985106-cb7ed400-7a80-11e9-9d79-80a3a1876582.png)

**_What should I do to resolve this?_**

**Comment by Dman95** [comment]
See SASM/Projects/MASMHello.asm for examples of MASM code.
