### ISSUE TITLE
Makefile?

### ISSUE THREAD

**Issue by m-boli** [Dman95/SASM#126]
Tried to build a new version of SASM on Centos. Last version I used was something like 3.9.0
The new source distribution does not include Makefile.
What to do?

**Comment by HackHex** [comment]
Hi, everyone!

**Comment by FuTuL** [comment]
Just do as readme says. run `qmake` -> `make` -> `make install`

**Comment by ximir** [comment]
Здравствуйте.
Меня  сейчас  нет  на  месте, вы  можете 
самостоятельно скачать инструкцию с яндекс диска пройдя по этой ссылке:https://yadi.sk/i/it0o5qDepoarm

**Comment by Konovaloff** [comment]
Айрдроп на 16$, но можно и больше получить. Регистрируетесь, проходите KYS и выводите токены на эфир кошелекhttps://clck.ru/HyQroМожно неплохо заработать.25 сент. 2019 г. 12:26 AM пользователь FuTuL <notifications@github.com> написал:Just do as readme says. run qmake -> make -> make install

**Comment by Konovaloff** [comment]
Айрдроп на 16$, но можно и больше получить. Регистрируетесь, проходите KYS и выводите токены на эфир кошелекhttps://clck.ru/HyQroМожно неплохо заработать.25 сент. 2019 г. 12:31 AM пользователь ximir <notifications@github.com> написал:Здравствуйте.

Меня  сейчас  нет  на  месте, вы  можете 

самостоятельно скачать инструкцию с яндекс диска пройдя по этой ссылке:https://yadi.sk/i/it0o5qDepoarm
