### ISSUE TITLE
Problema con idioma

### ISSUE THREAD

**Issue by alandelafuente** [Dman95/SASM#127]
Hola, quisiera saber cómo puedo cambiar el idioma a inglés de SASM, porque me aparece en ruso y cuando voy a la configuraciones y elijo inglés, vuelve a ponerse en ruso. Utilizo Ubuntu 18.04. Gracias.

**Comment by Lester2763** [comment]
Hola No tengo idea de cómo funciona tu sistema. Uso Windows 10, mi sistema funciona muy bien para mí. Tal vez deberías intentar usar Windows.


??

________________________________

**Comment by Dman95** [comment]
You can change language in the settings. Use translator.
