### ISSUE TITLE
Crash on Windows when clicking right button on empty place in memory.

### ISSUE THREAD

**Issue by p182** [Dman95/SASM#128]

**Comment by lberserq** [comment]
Can you provide a crash dump? You can collect it either with windbg or via WER 
https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps

**Comment by ximir** [comment]
Здравствуйте.
Меня  сейчас  нет  на  месте, вы  можете 
самостоятельно скачать инструкцию с яндекс диска пройдя по этой ссылке:https://yadi.sk/i/it0o5qDepoarm
