### ISSUE TITLE
Potential parsing error - unknown register

### ISSUE THREAD

**Issue by RaduNico** [Dman95/SASM#129]
Hello!

I am encountering an error in SASM 3.10.1 with Xubuntu 16.04 while running the debugger with the registers shown. The bug can be triggered by calling an externally defined function that contains a fgets call:

```
#include <stdio.h>
int* get(void)
{
    char input[20];
    fgets(input, 20, stdin);
    return NULL;
}
```

This code is compiled with `gcc -m32 file.c -o file.o -c` and linked from the build options menu. The code executes correcly, if you start the debugger it will run line by line with no issues, however if you do Debug -> Show registers, it will run with no issues until you hit the `call get` function. An assembly code which triggers this bug would be:

```
extern get

section .text
global main
main:
    mov ebp, esp; for correct debugging
    ;write your code here
    mov eax, 1
    call get
    
    mov eax, 2
    ret
```

After it passes the `call get` line, both si and ni will send an `unknown register: <address>` error, where address is the current eip, the registers will be printed in the output section and the register column will not be properly updated. I can provide additional debug information if needed

gdb : GNU gdb (Ubuntu 8.2-0ubuntu1\~16.04.1) 8.2
gcc : gcc version 5.5.0 20171010 (Ubuntu 5.5.0-12ubuntu1~16.04)

Radu

**Comment by RaduNico** [comment]
I've found a simpler way of triggering the bug. Running the debugger with show registers on the following program will print 'unknown registers' and dump gdb output in the Output field:

<code>
%include "io.inc"

section .bss
    str_stdin:  resb 4

section .text
global main
main:
    mov ebp, esp; for correct debugging
    GET_STRING str_stdin, 4
    PRINT_STRING str_stdin ; The bug triggers after this line
    xor eax, eax
    ret
</code>

**Comment by RaduNico** [comment]
It seems to be from the gdb version, as previously mentioned I am using gdb v 8.2. Installing gdb v7.11 fixes the issue:

<code>
wget "http://ftp.gnu.org/gnu/gdb/gdb-7.11.tar.gz"
tar -xvzf gdb-7.11.tar.gz
cd gdb-7.11
./configure
make -j4
sudo make install
</code>

**Comment by Dman95** [comment]
Problem fixed and will be available soon in the next release.
