### ISSUE TITLE
Can't build .exe using io64.inc in console

### ISSUE THREAD

**Issue by Ioloman** [Dman95/SASM#131]
I wrote my code in  windows 10 in SASM using io64.inc library for input/output. Now I need to build .exe file. I managed to assemble .obj file, but i don't know what library do I need to solve it. The gcc and golink linkers say:
Error!
The following symbols were not defined in the object file or files:-
printf
scanf
putchar
fgets
puts
fputs
fflush
get_stdin
get_stdout

If i use msvcrt.dll only get_stdin and get_stdout are left. Please, help, where do I find this functions?

**Comment by Dman95** [comment]
You can build exe in SASM using "File->Save .exe " option.

Actions which SASM performs during build are located on "Build" tab in settings.
