### ISSUE TITLE
Ошибка при компиляции

### ISSUE THREAD

**Issue by MuuNU** [Dman95/SASM#134]
Я пытаюсь запустить Example файл, поставляемый вместе с FASM (C:\FASM\EXAMPLES\DIALOG\DIALOG.ASM) и вылезает ошибка
Warning! Errors have occurred in the build:
c:/program files (x86)/sasm/mingw/bin/../lib/gcc/mingw32/4.6.2/../../../libmingw32.a(main.o): In function `main':
C:\MinGW\msys\1.0\src\mingwrt/../mingw/main.c:73: undefined reference to `WinMain@16'

Если отключаю GCC, то просто вылезает ошибка
[15:38:12] Build started...
[15:38:12] Warning! Errors have occurred in the build:

Обычным компилятором при запуске через FASMW.EXE из компилятора, идущего вместе с самим FASM запускается без каких либо проблем

**Comment by Dman95** [comment]
Подходящая Вам конфигурация сборки есть в справке.

В опциях ассемблера надо указать "$SOURCE$ $PROGRAM$ -s $LSTOUTPUT$" и включить опцию "Не запускать компоновщик".
