### ISSUE TITLE
CAN'T USE DEBUGGER ON LINUX MINT CINNAMON

### ISSUE THREAD

**Issue by HoriaCool** [Dman95/SASM#136]
Please help me ... I tried everything possible. I installed several versions of sasm, but I can use the debugger with neither of them. When I click on the debugger button I get the message "Debugging started ...", but I can not click anything after (Step over, Step in or Stop appears coloured in grey). Neither of shortcuts work (example breakpoint or show registers).

I mention that I installed all the dependencies needed for Linux: Qt 4.8, gcc (x86), gcc-multilib (x64), gdb, nasm, etc.

**Comment by Dman95** [comment]
The problem is in [the bug in gdb](https://stackoverflow.com/questions/58225562/how-to-fix-hang-in-gdb-in-ld-linux-so-2-when-running-a-32-bit-executable-on-a-64) 

> This problem has been fixed for Ubuntu in the gdb package version 8.1-0ubuntu3.2, so just upgrading your packages (sudo apt update && sudo apt upgrade) should help currently.
