### ISSUE TITLE
OBS Repository for OpenSUSE Tumbleweed unavailable

### ISSUE THREAD

**Issue by TrickyRicky26** [Dman95/SASM#137]
The repository for OpenSUSE Tumbleweed is no longer available (previously at https://download.opensuse.org/repositories/home:/Dman95/openSUSE_Tumbleweed/). However, repos for Leap 13.x, 15.x and 42.x are still available.

**Comment by Dman95** [comment]
Repository for OpenSUSE Tumbleweed enabled. Thanks for reporting!
