### ISSUE TITLE
Possible yasm support

### ISSUE THREAD

**Issue by Petross404** [Dman95/SASM#140]
Hello. Since yasm supports nasm syntax, it could be supported as a superset of nasm. Any idea on how to set this as workaround right now?

**Comment by sleirsgoevy** [comment]
A possible workaround is as follows:
```
mkdir fake_bin
ln -s `which yasm` fake_bin/nasm
PATH="$(pwd)/fake_bin:$PATH" /path/to/sasm
```

**Comment by sleirsgoevy** [comment]
EDIT: yasm seems to support emitting proper DWARF debug info. It may make sense using that for debugging.

**Comment by Dman95** [comment]
You could specify path to yasm in "Assembler path" and suitable options in "Assembly options" on "Build" tab in settings.
