### ISSUE TITLE
Problem with db and GET_DEC 1 

### ISSUE THREAD

**Issue by sensei12** [Dman95/SASM#143]
Hello,

I encountered a problem (The program crash) given the following code:

--------------------------
%include "io.inc"

section .data
var1 db 0x00

section .text
global CMAIN
CMAIN:
    ;write your code here
    GET_DEC 1, var1
    xor eax, eax
    ret
-----------------
This also occurs for GET_DEC 2 and GET_DEC 4

The problem also occurs for dw declaration but has not problem for dd

But, placing section .data at the end of the program will not cause the problem.

I am using SASM 3.11.1, WIndows 10 64-bit, NASM, x32

![SASM db error](https://user-images.githubusercontent.com/53364271/85850651-cd68aa00-b7df-11ea-96c2-ef51dc065301.png)

**Comment by Dman95** [comment]
Hello,

Fixed and will be available in the next release. Thanks!
