### ISSUE TITLE
Debugger stuck on when antivirus deletes binary

### ISSUE THREAD

**Issue by RedDragonWebDesign** [Dman95/SASM#146]
OS = Windows.

I clicked Debug -> Start. My antivirus detected the executable as a virus and quarantined it. After, SASM is stuck in debug mode, with no way to stop debug mode and try again. Pressing the continue button doesn't do anything.

Workaround: Restart the program.

Suggested fix: When the "continue" button is pressed, have the program check if the binary file (or thread/process) still exists. If not, automatically stop the debugging.

![2020-09-21_200159](https://user-images.githubusercontent.com/43397938/93840468-5bb8c480-fc45-11ea-8188-2f5dfc5d1ea4.png)

**Comment by Dman95** [comment]
Seems pretty rare case with hard recovery to normal state. Just set up your antivirus properly.
