### ISSUE TITLE
Tab character

### ISSUE THREAD

**Issue by RedDragonWebDesign** [Dman95/SASM#148]
I use tab instead of 4 spaces. When I copy/paste my code from my IDE into NASM, tab characters are 6.5 spaces wide. When I hit tab within the program, it inserts 4 spaces. So the code's indentation looks a little strange.

![image](https://user-images.githubusercontent.com/43397938/95052201-62165a00-06a3-11eb-93fc-e18ec71c0614.png)

Suggested Fix: Consider having tab use tab character (ASCII 9) instead of 4 spaces. Or consider having tab character display as 4 characters wide.

**Comment by Dman95** [comment]
Just setup replacing tabs with spaces in your IDE. Indentation using spaces is more convenient because looks same independently of editor.
