### ISSUE TITLE
Missing qt_pt.qm file for portuguese translation

### ISSUE THREAD

**Issue by alglus** [Dman95/SASM#150]
Hey! I have translated SASM into portuguese and everything seems to work fine. I would like to open a pull request, however I don't know, how to create the qt_pt.qm file.
When I run `lrelease language_pt.ts` or `lrelease SASM.pro` it only generates `language_pt.qm`, but not `qt_pt.qm`.

How can I find/generate that file, so that I can test the changes before submitting?

The changes so far are here: [SASM/portuguese-language](https://github.com/alglus/SASM/tree/portuguese-language).

**Comment by kerstinlieff** [comment]
UNSUBSCRIBE ME

**Comment by alglus** [comment]
> UNSUBSCRIBE ME

@kerstinlieff, there is no need to shout here. Please do some soul and internet searching and just manage your subscriptions:
https://docs.github.com/en/free-pro-team@latest/github/managing-subscriptions-and-notifications-on-github/viewing-your-subscriptions

**Comment by mmagdon** [comment]
Why am I getting this email

**Comment by pango3001** [comment]
Hello special people who all got this email even though none of us are
subscribed to this repo. I've been getting these emails for years now. Side
note, I will be graduating spring of 2021 with a BS in CS. Anyone hiring?

**Comment by armrha** [comment]
Yeah, there was a github bug a few years back that kept resubscribing
people for this repo for a certain subsection of users. There were tens of
thousands.  I got tired of unsubscribing so I too am here for the long
haul, hope the project continues well.

**Comment by kerstinlieff** [comment]
Great question...and you can’t even get off their mailing list!

**Comment by smithricharde61** [comment]
This email is coming to my husband who died in February, please remove him.

**Comment by mickeyslaven** [comment]
Unsubscribe me too please. I’m stuck in here too😂

Thanks
-Mickey

**Comment by alglus** [comment]
**@all_with_subscription_problems**
Up front: no one can remove a subscription for you.
If just deleting an incoming e-mail and moving on is not an option for you, then maybe:

1. Set up a filter in your e-mail client, so that all notifications from this repository get deleted automatically.
2. Report the problem to GitHub. If there are indeed tens of thousands affected and at least 10% of you report it, it ought to be noticed by the website and hopefully solved.

Because, just face it, leaving pitiful comments on new issues will not solve your problem. You will keep receiving new notifications, unless this repository is deleted, which I hope it won't.
But by moaning here you are, in fact, spamming all those, who really want to get meaningful updates from this repository and help improve it.

**Comment by GuruShankar** [comment]
Why am I getting these emails? Please remove me from the mail chain
