### ISSUE TITLE
Portuguese translation

### ISSUE THREAD

**Issue by nalves599** [Dman95/SASM#152]
Create a translation to portuguese.

**Comment by alglus** [comment]
Duplicate of #150

**Comment by emendblu** [comment]
I don’t need a Portuguese translation right now. Can you send over the original please and I will use my Portuguese-English dictionary to translate if needed.

**Comment by votemikejones** [comment]
I  need the Portuguese version tonight or we’re going to lose A OT of money $$$$$$$



What’s our eta?

**Comment by emendblu** [comment]
How much money are we talking? I got a guy standing by, he don’t speak the language but I have faith he can get it done

**Comment by nalves599** [comment]
I have the translation already done. I can create a pull request.

**Comment by GuruShankar** [comment]
HI .. I am not sure y I am receiving these emails.. ? please unsubscribe me

**Comment by emendblu** [comment]
Don’t be modest. You are an important part of this team and deserve to get updates just as much as everyone else.
