### ISSUE TITLE
SASM (3.11.1) Debug not working on Ubuntu 20.04

### ISSUE THREAD

**Issue by rjsargeant** [Dman95/SASM#155]
Debug begins with the message "Debugging started", however no line is highlighted.  All "Debug" menu items remain disabled except "Continue" which has not effect.  No error messages are shown.  However the same version works great on Windows.  I suspect this is the same problem highlighted by other on Arch linux.

**Comment by votemikejones** [comment]
M

**Comment by rjsargeant** [comment]
This is the approach which finally worked for me.  Use Ubuntu 18.04-5 not 20.04.  Download sasm_3.11.1_amd64.deb.  Try to install using "sudo dpkg -i sasm-3.11.1_amd64.deb".  This will indicate a series of dependencies missing.  Then follow up with "sudo apt --fix-broken install".  Finally repeat "sudo dpkg -i sasm_3.11.1_amd64.deb".  I hope this helps others.

**Comment by Lester2763** [comment]
Why am I getting this from you ...?

.
________________________________

**Comment by votemikejones** [comment]
Mike Jones
Owner & Creative Director, Scissortail Creative
405.928.1986 | mike@scissortailcreative.us

**Comment by emendblu** [comment]
Because you are now on the team!

**Comment by smithricharde61** [comment]
Please remove this email, my husband is dead

**Comment by Dman95** [comment]
Try new built package for Ubuntu 20.04 and install it using Software Install (double click): https://download.opensuse.org/repositories/home:/Dman95/xUbuntu_20.04/amd64/sasm_3.12.0-1_amd64.deb

Everything seems to be working.

**Comment by fila43** [comment]
same issue on fedora 33

**Comment by Dman95** [comment]
Fixed in version 3.12.1. To apply the fix update SASM and reset settings: Settings -> Common -> Reset all.
