### ISSUE TITLE
Using 'SEGMENT' crashes SASM in DEBUG mode

### ISSUE THREAD

**Issue by starbassma** [Dman95/SASM#161]
Hello,
We can read from the[ NASM DOC](https://www.nasm.us/xdoc/2.10.07/html/nasmdoc6.html#section-6.3) :

> (SEGMENT is an exactly equivalent synonym of SECTION)

But when SEGMENT is used instead of SECTION, the debug crashes SASM.

With _'SECTION'_ the debug mode works fine as expected :

![section](https://user-images.githubusercontent.com/6652482/109423840-5c6a3980-79e1-11eb-89d3-6142e3391793.png)

But when _'SEGMENT'_ is used instead of _'SECTION'_, the code **runs fine**, but **crashes through the debugger**  :cold_sweat:

![segment](https://user-images.githubusercontent.com/6652482/109423999-2083a400-79e2-11eb-84b5-fef0a05f3e7e.png)

OS Logs :

**apport**: `ERROR: apport (pid 9742) Sun Feb 28 16:15:02 2021: executable: /usr/bin/sasm (command line "sasm")`

**syslog**: `Feb 28 16:15:02 guest-HP-Pc kernel: [21369.914586] sasm[9602]: segfault at 38 ip 000055ea8b4d1647 sp 00007ffc81418570 error 4 in sasm[55ea8b47d000+16c000]`

Best regards,
Wassime.

**Comment by starbassma** [comment]
behavior observed in last stable release V3.12.1

**Comment by votemikejones** [comment]
Segment is such a little bitch!

[image: giphy.gif]

>

**Comment by starbassma** [comment]
Hi @Dman95 ,
Please have a look,
Best Regards,
Wassime.

**Comment by emendblu** [comment]
I hope this is a joke. You gotta do a lot better than whatever this nonsense is!

**Comment by starbassma** [comment]
Unfortunately a lot spam accounts on Github..

**Comment by emendblu** [comment]
Up your game my man!

**Comment by Dman95** [comment]
Fixed.

**Comment by piper4hire** [comment]
wow  - so much spam.
