### ISSUE TITLE
An error has occurred in the debugger. Please check the names of the sections 

### ISSUE THREAD

**Issue by YosraDaso** [Dman95/SASM#163]
Hello,
I use SASM 3.12.1
I get always this: {
[20:59:23] Debugging started...
An error has occurred in the debugger. Please check the names of the sections.
[20:59:23] Debugging finished.
}
and because of it I can't do CTRL+M/R

I used another laptop and everything worked fine
I would like to know what I need to do in my laptop to fix this problem (my laptop: 64 bit operation system)
In SASM I use: mode x64, assembler NASM

**Comment by piper4hire** [comment]
wow  - so much spam.
