### ISSUE TITLE
Manual compilation returns " undefined reference to 'get_stdout' "

### ISSUE THREAD

**Issue by iwakura1ain** [Dman95/SASM#164]
When compiling manually in a terminal, the attached include files are not recognized.

`sudo nasm -f elf64 hello_sasm.asm -o hello_sasm.o`                                                          

`gcc -no-pie -m64 -o hello_sasm hello_sasm.o`       
>hello_sasm.o: In function `..@25.after_data':                                                              >hello_sasm.asm:(.text+0x76): undefined reference to `get_stdout'                                           >collect2: error: ld returned 1 exit status

Even after manually adding io64.inc and io.inc into the project directory, it still does not work.

**Comment by anonymix007** [comment]
That's because io*.inc files use these functions. 
You could create macro.c file:
```
#include <stdio.h>
FILE *get_stdin(void) { return stdin; }
FILE *get_stdout(void) { return stdout; }
```
Compile it to macro.o, and then use GCC to link this object file with your own.
You could also take a look at [script](https://github.com/Dman95/SASM/files/6327871/build_asm.zip) that compiles assembly to elf32, but with some minor modifications it could produce 64 bit executables too

**Comment by votemikejones** [comment]
Y'all have one last chance to remove me from this list before I write a
script to overload you with memes.

Also, y'all work in IT and just release sometimes proprietary info like
this? I could easily attack your application and know the weak points
thanks to these emails.

**Comment by nirvdrum** [comment]
@votemikejones If you're getting emails from this project, it's because you're watching it. You can either stop watching it or change [your notification settings](https://github.com/settings/notifications) to disable email notifications for all projects.

**Comment by votemikejones** [comment]
You’re fancy “programmers” - take me off your list if you don’t want any more of my delicious memes.

**Comment by emendblu** [comment]
You are part of this project. It is expected that you stay up to date on every aspect of it.

**Comment by emendblu** [comment]
Opened!
