### ISSUE TITLE
Allow "push rbp" as first assembly statement

### ISSUE THREAD

**Issue by nirvdrum** [Dman95/SASM#168]
When attempting to debug a function, SASM will automatically add `mov rbp, rsp` as the first statement, unless that's already the first statement. But, a common function preamble is:

```asm
push    rbp
mov     rbp, rsp
```

In this case, SASM unnecessarily adds the `mov` statement and leads to:

```asm
mov     rbp, rsp
push    rbp
mov     rbp, rsp
```

**Comment by Dman95** [comment]
Fixed.
