### ISSUE TITLE
The word being found is highlighted after it is modified

### ISSUE THREAD

**Issue by NaNAGISaSA** [Dman95/SASM#170]
You could reproduce the bug in the following process:
1. Press the word which is to be found, such as `example`;
2. Press *ctrl + F*, input the word `example` and click *Find all*;
3. modify the word, for example, delete the character `ple`, or input some other characters, for example, `qwer`;
4. in both cases above, the region highlighted are wrong, the word being highlighted will be `exam` or `exampleqwer`, as below:

![3](https://user-images.githubusercontent.com/42483928/118914142-4a9f8f00-b95d-11eb-84c0-7be5a0af38ea.png)

**Comment by emendblu** [comment]
How could you let a bug like this happen?

**Comment by NaNAGISaSA** [comment]
> How could you let a bug like this happen?
> […](#)
> Sent from my iPhone
> On May 19, 2021, at 11:21 PM, NaNAGISaSA ***@***.***> wrote: ﻿ You could reproduce the bug in the following process: Press the word which is to be found, such as example; Press ctrl + F, input the word example and click Find all; modify the word, for example, delete the character ple, or input some other characters, for example, qwer; in both cases above, the region highlighted are wrong, the word being highlighted will be exam or exampleqwer, as below: — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I think the process is clear enough. Anywhere you do not understand?

**Comment by emendblu** [comment]
We need this fixed yesterday!

**Comment by votemikejones** [comment]
Can’t believe someone actually said they wanted something fixed yesterday. 

You do realize talking like that almost guarantees they slow rolled fixing this, right?

**Comment by emendblu** [comment]
I don’t want excuses I want results! This project is no small thing for me. I cannot be embarrassed by bugs like this when I try to demonstrate the various use cases! This could have cost us real money!

**Comment by grayglass** [comment]
who the hell are you and what does it have to do with me
________________________________

**Comment by emendblu** [comment]
I’m the guy who demands you fix this bug immediately!

**Comment by brawnerquan** [comment]
I think this guy is trolling

**Comment by emendblu** [comment]
I just want to see results

**Comment by toddwhitmarsh** [comment]
I will never EVER say I want off this thread :-)

**Comment by Dman95** [comment]
Fixed.
