### ISSUE TITLE
Windows - linker errors - first install 

### ISSUE THREAD

**Issue by zb-z** [Dman95/SASM#171]
Are there some prerequisites that are not listed, or maybe the setup binary is terribly old ?
The reason I ask is that I see all binaries inside ...\SASM\... having a 2015 timestamp

https://github.com/Dman95/SASM/releases/download/v3.12.1/SASMSetup3121.exe

Microsoft Windows [Version 10.0.18363.1500]

There is a Visual Studio 2017 installed on the box but it wasn't running

[22:26:40] Warning! Errors have occurred in the build:
c:/bin/sasm/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.1/../../../../x86_64-w64-mingw32/lib/../lib/libmingw32.a(lib64_libmingw32_a-crt0_c.o):crt0_c.c:(.text.startup+0x25): undefined reference to `WinMain'

**Comment by piper4hire** [comment]
wow  - so much spam.
