### ISSUE TITLE
Option "Build in current directory" has no effect

### ISSUE THREAD

**Issue by leunMar** [Dman95/SASM#173]
Or at least I cannot see it. The output files are always located in `/tmp/SASM/`. Can anybody help me out?

My build options:
![Screenshot from 2021-07-30 12-39-01](https://user-images.githubusercontent.com/36481640/127641578-5eb2a42f-617e-4ae6-8130-a7a3e62c198a.png)

**Comment by mariusvn** [comment]
I can confirm on windows

**Comment by Dman95** [comment]
This option influences on working directory for building, not on resulting binary location. This option is needed for including libraries from current directory.

**Comment by piper4hire** [comment]
wow  - so much spam.
