### ISSUE TITLE
Bug: Debugging does not work when .gdbinit is present in home directory.

### ISSUE THREAD

**Issue by McBride-SallyJoeBob** [Dman95/SASM#176]
Environment: [Ubuntu 20.04 LTS] GDB 9.2

Steps to reproduce: Added .gdbinit file to home directory which gives custom GDB ui. Ran SASM with the following options

assembly options: -f elf -gstabs $SOURCE$ -l $LSTOUTPUT$ -o $PROGRAM.OBJ$
linking options: -o $PROGRAM$ -m elf_i386 $PROGRAM.OBJ$
Assembler path: nasm
linker path: ld

Expected behavior: Debugger launches normally, allowing to view registers memory and breakpoints and debug.

Actual behavior: Debugger freezes after successful build. Registers and memory are greyed out and none of the debug commands work.

Possible solution: Use gdb -nx to always avoid gdbinit no matter what. For the class I am using this software in, we often need to add a gdbinit file because we are debugging a QEMU emulator. As a result any time I want to debug using SASM, I must first remove the .gdbinit file before proceeding.

**Comment by Dman95** [comment]
Fixed.

**Comment by piper4hire** [comment]
wow  - so much spam.
