### ISSUE TITLE
Debogguer ne fonctionne pas lorsque j'utilise des GET_ sur windows11

### ISSUE THREAD

**Issue by Soxomer** [Dman95/SASM#178]
A chaque fois que j'utilise un Get le deboguer plante 
![Probleme_GET](https://user-images.githubusercontent.com/96873044/147753860-00918659-e96c-46ab-8fca-32cbb3fada69.png)
En revanche si je le lance normalment et pas avec le debuggeur tout fonctionne correctement

**Comment by piper4hire** [comment]
wow  - so much spam.
