### ISSUE TITLE
SASM hangs after File/Save as

### ISSUE THREAD

**Issue by DudeMcGee** [Dman95/SASM#181]
When I start SASM and enter some code, building and executing works fine. As soon as I enter `File, Save as` in the menu, SASM hangs and its window can't even be closed anymore. I have to kill -9 the SASM process. Moreover, SASM works in the directory `/run/user/1000/doc/349f48/` instead of my home directory or another plausible directory.

**Comment by gpanchan** [comment]
Unsubscribe

**Comment by piper4hire** [comment]
thats some spam alright

-S

**Comment by Dman95** [comment]
Check that you have proper rights for saving file to the directory.
