### ISSUE TITLE
Latest .exe results in an antivirus warning in edge

### ISSUE THREAD

**Issue by Dark-Zeus** [Dman95/SASM#182]
downloading version 3.12.2 results in "SASMSetup3122.exe isn't commonly downloaded. make sure you trust SASMSetup3122.exe before opening it."

**Comment by piper4hire** [comment]
awesome but one question: what on earth is SASM?

**Comment by emendblu** [comment]
You better get on board man! You are part of this project now!

**Comment by votemikejones** [comment]
Been part of this godforsaken group a while now. Happy Friday y’all.

**Comment by armrha** [comment]
You too buddy. It’s been amusing to see the group of people earnestly
working on this along with the several thousand people Github added for no
reason.

**Comment by bitcubed** [comment]
Bruh i don’t even code

**Comment by votemikejones** [comment]
Apparently, neither do these folks.

**Comment by piper4hire** [comment]
great! do I get a t-shirt or something?

**Comment by emendblu** [comment]
I feel like we need to delete everything and start again from scratch.

**Comment by piper4hire** [comment]
there is simply no escaping this hellscape
