### ISSUE TITLE
The executable file is built in the /tmp directory.

### ISSUE THREAD

**Issue by panfilovkv** [Dman95/SASM#185]
The executable file is built in the /tmp directory. Attempting to specify an explicit path results in a FASM write error. Archlinux-5.16

**Comment by piper4hire** [comment]
this works fine on my C-64.

**Comment by piper4hire** [comment]
SPAM SPAM SPAM SPAM SPAM SPAM SPAMOn Feb 6, 2023, at 1:46 AM, Dmitriy Manushin ***@***.***> wrote:﻿
Closed #185 as completed.
