### ISSUE TITLE
Warnings in builder ?

### ISSUE THREAD

**Issue by aguytech** [Dman95/SASM#187]
uname -a
`Linux 970a 5.15.32-1-MANJARO #1 SMP PREEMPT Mon Mar 28 09:16:36 UTC 2022 x86_64 GNU/Linux`
sasm 3.12.2

When I try to build the simple following code manually, it works fine but not in sasm ?
```
bits 32

section .data
    message db "Hello World!", 10

section .text
    global _start
    _start:
        mov eax, 4
        mov ebx, 1
        mov ecx, message
        mov edx, 12+1
        int 0x80

        mov eax, 1
        mov ebx, 0
        int 0x80
```

```
nasm -g -f elf32 test2.asm -l list
ld test2.o -m elf_i386 -o test2
./test2
Hello world !
```
Here is my sasm configuration:

- -g -f elf32 $SOURCE$ -l $LSTOUTPUT$ -o $PROGRAM.OBJ$
- Build in current directory
- Disable linking

I'm looking for logs file and I did not found
I tried an other simple code with the same result ?

Thank you for any help ;o)

**Comment by aguytech** [comment]
here is the error message in sasm:
```
[07:43:20] Build started...
[07:43:20] Warning! Errors have occurred in the build:
```

**Comment by votemikejones** [comment]
I’ve decided if you don’t fix your shit soon I’m going to start sending all of your internal shit I’ve collected to a competitor and a federal regulator. Get your shit together. Fucking losers.

**Comment by votemikejones** [comment]
SPAM him back at ***@***.***

Currently signing him up for everyone annoying list I can find. 

Small time asshole who can stop these emails but hasn’t. 

http://dman95.github.io/

**Comment by votemikejones** [comment]
Here’s another idea.

Log in / sign up for GitHub and submit a TON of tickets to this guy. Let him know what it feels like to get spammed and the spammer not give a fuck. 

https://github.com/Dman95/SASM

**Comment by Dman95** [comment]
You shouldn't disable linking. You should link it with ld and specify correct linking options for it (see help): $PROGRAM.OBJ$ -m elf_i386 -o $PROGRAM$
