### ISSUE TITLE
How do you get SASM to save a .lst file?

### ISSUE THREAD

**Issue by JeffDuntemann** [Dman95/SASM#189]
I've just discovered SASM and am working through all its features. So far I like it a _lot_.

I'm using NASM. Here's the issue: Although there's the term -l $LSTOUTPUT$ in SASM's default assembly options line, as best I can tell no .lst file is generated during a successful build. When I build the same ,asm file from the console using a conventional makefile including the -l option, I get a .lst file.

Is there a way to generate a .lst file from a SASM build?

Many thanks for any advice here.

**Comment by piper4hire** [comment]
wait … SASM is a real thing? I thought this was all just a spam engine. All I know is that Dimitriy is a horrible troll-like creature.
