### ISSUE TITLE
Debbugger ASCII addon

### ISSUE THREAD

**Issue by BAT-Vanquisher** [Dman95/SASM#191]
Hi, great software!

Would it be possible for the debugger memory window to incorporate an ASCII option in the type selection option please.

e.g. 
current options are

        SMART option converts Hello world to Helloworld
        CHAR option converts hello world to 72'H',101'e',108'l',108'l',111'o',32'',119'w',111'o',114'r',108'l',100'd

requested 

        ASCII option would convert Hello world to Hello world 

      
Many thanks

Roland!

**Comment by piper4hire** [comment]
welcome to the bottomless pit of spam.

**Comment by Dman95** [comment]
Hello. SMART option fixed in version 3.13.0. Thank you!
