### ISSUE TITLE
couldnt work on macos

### ISSUE THREAD

**Issue by haliang0409-cmd** [Dman95/SASM#192]
when I try to compile something, it always warns me:
Directory NASM does not exist. Please reinstall the program.
the nasm has been installed on my macbook, even if I reinstalled it, I still cant let it work on it.

**Comment by piper4hire** [comment]
does anyone even know what SASM is? I think it’s just made up.

**Comment by mickeyslaven** [comment]
Dman95 knows, but he keeps us trapped in here

**Comment by piper4hire** [comment]
what kind of person would do such a thing?

-S

**Comment by Dman95** [comment]
Probably you need to place NASM directory near SASM executable. Read the instructions about installing SASM on Mac on the site.
