### ISSUE TITLE
windows11 sasm "Unable to start assembler. Check your settings."

### ISSUE THREAD

**Issue by ZouAgTao** [Dman95/SASM#193]
Hi
I have a `Windows 11` and just installed our SASM 3.12.2  with zip release.
It worked and I could start our SASM.
But if I try to compile even with the demo code

```ASM
%include "io.inc"

section .text
global CMAIN
CMAIN:
    ;write your code here
    xor eax, eax
    ret
```

The console of SAMA will always gives me:

`Unable to start assembler. Check your settings.`

My setting is below, if it is necessary to post my other information, just tell me, thanks!
![图片](https://user-images.githubusercontent.com/32996464/187330012-ee99bd33-a635-4965-9744-f69c99e9283f.png)

**Comment by piper4hire** [comment]
what the hell is SASM?? 

-S

**Comment by votemikejones** [comment]
- SASM
