### ISSUE TITLE
Debug mode / Functions C do not work

### ISSUE THREAD

**Issue by darioradu** [Dman95/SASM#194]
I'm trying to run a basic program that prints a hello world message to the console using the puts function.The program works fine while executing it with "Build and run" option, I mean the message is displayed in the Output. 
![image](https://user-images.githubusercontent.com/41400460/193721879-e8975d3c-8144-4d3a-a6ee-5b6d11644bb5.png)

But if i use the "Debug" option, the program runs but the message is not displayed in the output 
![image](https://user-images.githubusercontent.com/41400460/193722153-ed215a3b-e296-447f-822f-cfe14aca516d.png)

I'm working on Windows 10 64 bits
SASM  version 3.12.2
See the Build tab options configured: 
![image](https://user-images.githubusercontent.com/41400460/193722256-15781607-70b3-4d87-9677-fa7c34c8a0c7.png)

**Comment by Dman95** [comment]
It's because output is buffered. You need to call fflush(stdin) to get output immediately like this:
```
%include "io64.inc"

global main
extern puts
extern fflush
extern get_stdout

section .data
message db "Hello World", 0

section .text
main:
    mov rbp, rsp
    sub rsp, 32
    mov rcx, message
    call puts
    call get_stdout
    mov rcx, rax
    call fflush
    add rsp, 32
    ret
```
