### ISSUE TITLE
I created a kind of "dark theme"

### ISSUE THREAD

**Issue by hruzgar** [Dman95/SASM#196]
I hate white background, black text so i modified the settings in sasm and found a method to make a bash script, which automates the process..
[This](https://github.com/hruzgar/sasm-dracula)
Could you guys link this somewhere on the website so other people with the same problem could use this?

**Comment by Dman95** [comment]
Dark theme added in the settings in SASM 3.14.0. Thank you.

**Comment by piper4hire** [comment]
will it never end?On Mar 3, 2023, at 6:11 AM, Dmitriy Manushin ***@***.***> wrote:﻿
Dark theme added in the settings in SASM 3.14.0. Thank you.

**Comment by Dman95** [comment]
> will it never end?On Mar 3, 2023, at 6:11 AM, Dmitriy Manushin ***@***.***> wrote:﻿ Dark theme added in the settings in SASM 3.14.0. Thank you. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Just log in your github profile and unsubscribe.
