### ISSUE TITLE
Set correct file name hint in save file dialogs

### ISSUE THREAD

**Issue by Disasm** [Dman95/SASM#26]
For example, in .asm save file dialog it must be something with ".asm" extension, not ".exe". Same thing for saving .exe files.

**Comment by ThomasThelen** [comment]
I'm having the same problem. Currently .exe files, although specified as .exe in the filetype menu, Also, the assembly files being saved aren't showing up in the file explorer, only through the SASM open file context which is strange.

Temporary work arounds:

1. .exe Files
     Add the .exe extension after the filename
2. .asm Files
     Add the .asm file extension and save somewhere other than the SASM folder.

**Comment by Dman95** [comment]
Fixed.
