### ISSUE TITLE
SASM Windows won't build

### ISSUE THREAD

**Issue by weaknetlabs** [Dman95/SASM#32]
Hello, I looked through the issues and didn't see this one, opened or closed. I am using the latest Windows binary for SASM and cannot build any of my NASM code. I get an undefined reference to WinMain16:

[21:07:09] Build started...
[21:07:09] Warning! Errors have occurred in the build:
c:/program files (x86)/sasm/mingw/bin/../lib/gcc/mingw32/4.6.2/../../../libmingw32.a(main.o): In function `main':
C:\MinGW\msys\1.0\src\mingwrt/../mingw/main.c:73: undefined reference to `WinMain@16'

In the configuration (default, just installed it) The 3 settings are:

assembly options: -g -f win32 $SOURCE$ -l $LSTOUTPUT$ -o $PROGRAM.OBJ$
linking options: $PROGRAM.OBJ$ $MACRO.OBJ$ -g -o $PROGRAM$ -m32
nasm path: C:/Program Files (x86)/SASM/NASM/nasm.exe
linker path: C:/Program Files (x86)/SASM/MinGW/bin/gcc.exe

Is there a library that includes `WinMain@16' that I need to include in my assembler options? Sorry if this is a dumb question, I am new to NASM in Windows (usually do it with vim/ld/nasm).

Thank you and great project btw! :)

**Comment by weaknetlabs** [comment]
Ok. Duh. Windows requires a "_main" and I never used that name before (always used somehing like "_start" etc). It compiled fine when I changed that. I should have read your "Help" section a lot sooner, I am sorry. :(

**Comment by Valdrinium** [comment]
This helped a lot
