### ISSUE TITLE
Add io.inc includes similar to the nasm's one for other compilers

### ISSUE THREAD

**Issue by insolor** [Dman95/SASM#37]
I think I can implement io.inc for fasm if you describe in brief how io.inc for nasm works (I don't understand nasm's macros syntax).

**Comment by Dman95** [comment]
You can find a description of the library on the site http://dman95.github.io/SASM/english.html
In brief, macros determine a type of the arguments and call an according code, in which C library functions are used.

**Comment by insolor** [comment]
I've already seen the docs from the link you given.
I need something else: at least I need info on how to make basic IO functions work.
Eg. I've written the following code:

```assembly
format ELF

extrn _printf

section '.text' executable
public _main
_main:
    push message
    call _printf
    xor eax, eax
    ret

message db 'Hello!', 0
```

It is compiled successfully with fasm from sasm, but when I try to run it, it prints nothing.

**Comment by insolor** [comment]
I finally found helloworld for fasm, it works fine, so I will try to use it as a reference.

**Comment by insolor** [comment]
printf, puts are working, but I failed to make work scanf - it just passes through it without waiting of input.

**Comment by Dman95** [comment]
It is not a bug, it is a feature. To perform input in a program you should enter a text before running a program.

**Comment by ThomasThelen** [comment]
There are many libraries that have already been made for other assemblers. Look up FreshLib for a fasm macro library.

**Comment by insolor** [comment]
@ThomasThelen, the request was not about libraries for fasm in general. It was limited to rewriting existing io.inc file, which works with nasm, to the syntax of fasm.
Personally I don't need such include file for using in my projects, but I think it would be useful for some people for educational purposes.
