### ISSUE TITLE
Link external library (like visual studio does)?

### ISSUE THREAD

**Issue by grickel** [Dman95/SASM#38]
I really like the way SASM looks, works and see big potential for SASM. 
I have a two questions.
First for the MASM assembler it is says MASM32 for assembler and linker path. Is the assembler using the authentic Microsoft Macro Assembler or is it using the open source one (Open Watcom Assembler)?
If it is not using the Microsoft Macro Assembler can you make an update which will use that assembler and linker?
  
Secondly, I would like to use the external library that comes with my textbook Assembly Language for x86 Processors (7th Edition). The libray that I am using comes from here http://kipirvine.com/asm/examples/index.htm
"Example programs and link library source code for the Seventh Edition, using Visual Studio 2012 or 2013" 
I believe the library is meant to specifically work with visual studio. Is there a way that it could be linked with SASM? 

Thank you for your time
And keep up the great work with SASM :)

**Comment by Dman95** [comment]
1) SASM supports MASM32 assembler, which you can download from site http://www.masm32.com/
2) In SASM you can set up commands for 2 steps of building (assembling and linking). Now I don't have Windows to test building with this library. You can try to set up building yourself.

**Comment by onebree** [comment]
Any update on this issue? I need to use an irvine library as well. (And the `inc` files)

@grickel I do not think the libs are specific to VCS. Rather, the author may just recommend that software for Windows users.

**Comment by ThomasThelen** [comment]
SASM uses the Microsoft Macro Assembler and Linker (ML.exe)  by default.
To change the default assembler and linker go to Settings->Settings->Build and change the paths.

Are you sure that the files being included are in a specified directory? You may have to define the directory of the included files or change their location to an already defined one.

**Comment by Dman95** [comment]
Assume, that Irvine library is located in folder "C:\irvine".

To use Irvine library you should select MASM assembler and set linking options to "/SUBSYSTEM:CONSOLE /OPT:NOREF /NOLOGO /OUT:$PROGRAM$ $PROGRAM.OBJ$ C:\irvine\irvine32.lib C:\irvine\kernel32.lib C:\irvine\user32.lib".

Also, when you include inc file using directive "INCLUDE", you should specify full path to it (e.g., "INCLUDE C:/irvine/Irvine32.inc").
