### ISSUE TITLE
Can not compile current source

### ISSUE THREAD

**Issue by MikeyG** [Dman95/SASM#42]
I pulled the current source, ran qmake, and make. Received the following:

/usr/lib64/qt4/bin/uic settings.ui -o ui_settings.h
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. -o main.o main.cpp
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. -o mainwindow.o mainwindow.cpp
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. -o tab.o tab.cpp
In file included from tab.h:52:0,
                 from tab.cpp:41:
codeeditor.h: In member function ‘virtual void CodeEditor::dropEvent(QDropEvent*)’:
codeeditor.h:102:42: error: invalid use of incomplete type ‘const class QUrl’
             const QString &fileName = url.toLocalFile();
                                          ^
In file included from /usr/include/qt4/QtCore/qvariant.h:48:0,
                 from /usr/include/qt4/QtCore/qsettings.h:46,
                 from /usr/include/qt4/QtCore/QSettings:1,
                 from tab.h:46,
                 from tab.cpp:41:
/usr/include/qt4/QtCore/qmetatype.h:299:7: error: forward declaration of ‘const class QUrl’
 class QUrl;
       ^
In file included from /usr/include/qt4/QtCore/qnamespace.h:45:0,
                 from /usr/include/qt4/QtCore/qobjectdefs.h:45,
                 from /usr/include/qt4/QtCore/qobject.h:47,
                 from /usr/include/qt4/QtGui/qlayout.h:45,
                 from /usr/include/qt4/QtGui/qboxlayout.h:45,
                 from /usr/include/qt4/QtGui/QVBoxLayout:1,
                 from tab.h:44,
                 from tab.cpp:41:
/usr/include/qt4/QtCore/qglobal.h: In instantiation of ‘class QTypeInfo<QUrl>’:
/usr/include/qt4/QtCore/qlist.h:113:62:   required from ‘T& QList<T>::Node::t() [with T = QUrl]’
/usr/include/qt4/QtCore/qlist.h:245:57:   required from ‘const T& QList<T>::const_iterator::operator*() const [with T = QUrl]’
codeeditor.h:100:9:   required from here
/usr/include/qt4/QtCore/qglobal.h:2127:26: error: invalid application of ‘sizeof’ to incomplete type ‘QUrl’
         isLarge = (sizeof(T)>sizeof(void*)),
                          ^
In file included from /usr/include/qt4/QtCore/qobject.h:50:0,
                 from /usr/include/qt4/QtGui/qlayout.h:45,
                 from /usr/include/qt4/QtGui/qboxlayout.h:45,
                 from /usr/include/qt4/QtGui/QVBoxLayout:1,
                 from tab.h:44,
                 from tab.cpp:41:
/usr/include/qt4/QtCore/qlist.h: In instantiation of ‘void QList<T>::node_destruct(QList<T>::Node*, QList<T>::Node*) [with T = QUrl]’:
/usr/include/qt4/QtCore/qlist.h:758:68:   required from ‘void QList<T>::free(QListData::Data*) [with T = QUrl]’
/usr/include/qt4/QtCore/qlist.h:732:15:   required from ‘QList<T>::~QList() [with T = QUrl]’
codeeditor.h:100:9:   required from here
/usr/include/qt4/QtCore/qlist.h:431:31: warning: possible problem detected in invocation of delete operator: [-Wdelete-incomplete]
         while(from != to) --to, delete reinterpret_cast<T*>(to->v);
                               ^
/usr/include/qt4/QtCore/qlist.h:431:31: warning: invalid use of incomplete type ‘class QUrl’
In file included from /usr/include/qt4/QtCore/qvariant.h:48:0,
                 from /usr/include/qt4/QtCore/qsettings.h:46,
                 from /usr/include/qt4/QtCore/QSettings:1,
                 from tab.h:46,
                 from tab.cpp:41:
/usr/include/qt4/QtCore/qmetatype.h:299:7: warning: forward declaration of ‘class QUrl’
 class QUrl;
       ^
In file included from /usr/include/qt4/QtCore/qobject.h:50:0,
                 from /usr/include/qt4/QtGui/qlayout.h:45,
                 from /usr/include/qt4/QtGui/qboxlayout.h:45,
                 from /usr/include/qt4/QtGui/QVBoxLayout:1,
                 from tab.h:44,
                 from tab.cpp:41:
/usr/include/qt4/QtCore/qlist.h:431:31: note: neither the destructor nor the class-specific operator delete will be called, even if they are declared when the class is defined
         while(from != to) --to, delete reinterpret_cast<T*>(to->v);
                               ^
/usr/include/qt4/QtCore/qlist.h:433:32: error: invalid use of incomplete type ‘class QUrl’
         while (from != to) --to, reinterpret_cast<T*>(to)->~T();
                                ^
In file included from /usr/include/qt4/QtCore/qvariant.h:48:0,
                 from /usr/include/qt4/QtCore/qsettings.h:46,
                 from /usr/include/qt4/QtCore/QSettings:1,
                 from tab.h:46,
                 from tab.cpp:41:
/usr/include/qt4/QtCore/qmetatype.h:299:7: error: forward declaration of ‘class QUrl’
 class QUrl;
       ^
In file included from /usr/include/qt4/QtCore/qobject.h:50:0,
                 from /usr/include/qt4/QtGui/qlayout.h:45,
                 from /usr/include/qt4/QtGui/qboxlayout.h:45,
                 from /usr/include/qt4/QtGui/QVBoxLayout:1,
                 from tab.h:44,
                 from tab.cpp:41:
/usr/include/qt4/QtCore/qlist.h: In instantiation of ‘void QList<T>::node_copy(QList<T>::Node*, QList<T>::Node*, QList<T>::Node*) [with T = QUrl]’:
/usr/include/qt4/QtCore/qlist.h:711:92:   required from ‘void QList<T>::detach_helper(int) [with T = QUrl]’
/usr/include/qt4/QtCore/qlist.h:725:27:   required from ‘void QList<T>::detach_helper() [with T = QUrl]’
/usr/include/qt4/QtCore/qlist.h:122:94:   required from ‘QList<T>::QList(const QList<T>&) [with T = QUrl]’
/usr/include/qt4/QtCore/qglobal.h:2375:81:   required from ‘QForeachContainer<T>::QForeachContainer(const T&) [with T = QList<QUrl>]’
codeeditor.h:100:9:   required from here
/usr/include/qt4/QtCore/qlist.h:399:28: error: invalid use of incomplete type ‘class QUrl’
                 current->v = new T(*reinterpret_cast<T*>(src->v));
                            ^
In file included from /usr/include/qt4/QtCore/qvariant.h:48:0,
                 from /usr/include/qt4/QtCore/qsettings.h:46,
                 from /usr/include/qt4/QtCore/QSettings:1,
                 from tab.h:46,
                 from tab.cpp:41:
/usr/include/qt4/QtCore/qmetatype.h:299:7: error: forward declaration of ‘class QUrl’
 class QUrl;
       ^
In file included from /usr/include/qt4/QtCore/qobject.h:50:0,
                 from /usr/include/qt4/QtGui/qlayout.h:45,
                 from /usr/include/qt4/QtGui/qboxlayout.h:45,
                 from /usr/include/qt4/QtGui/QVBoxLayout:1,
                 from tab.h:44,
                 from tab.cpp:41:
/usr/include/qt4/QtCore/qlist.h:405:17: warning: possible problem detected in invocation of delete operator: [-Wdelete-incomplete]
                 delete reinterpret_cast<T*>(current->v);
                 ^
/usr/include/qt4/QtCore/qlist.h:405:17: warning: invalid use of incomplete type ‘class QUrl’
In file included from /usr/include/qt4/QtCore/qvariant.h:48:0,
                 from /usr/include/qt4/QtCore/qsettings.h:46,
                 from /usr/include/qt4/QtCore/QSettings:1,
                 from tab.h:46,
                 from tab.cpp:41:
/usr/include/qt4/QtCore/qmetatype.h:299:7: warning: forward declaration of ‘class QUrl’
 class QUrl;
       ^
In file included from /usr/include/qt4/QtCore/qobject.h:50:0,
                 from /usr/include/qt4/QtGui/qlayout.h:45,
                 from /usr/include/qt4/QtGui/qboxlayout.h:45,
                 from /usr/include/qt4/QtGui/QVBoxLayout:1,
                 from tab.h:44,
                 from tab.cpp:41:
/usr/include/qt4/QtCore/qlist.h:405:17: note: neither the destructor nor the class-specific operator delete will be called, even if they are declared when the class is defined
                 delete reinterpret_cast<T*>(current->v);
                 ^
/usr/include/qt4/QtCore/qlist.h:412:17: error: invalid use of incomplete type ‘class QUrl’
                 new (current) T(*reinterpret_cast<T*>(src));
                 ^
In file included from /usr/include/qt4/QtCore/qvariant.h:48:0,
                 from /usr/include/qt4/QtCore/qsettings.h:46,
                 from /usr/include/qt4/QtCore/QSettings:1,
                 from tab.h:46,
                 from tab.cpp:41:
/usr/include/qt4/QtCore/qmetatype.h:299:7: error: forward declaration of ‘class QUrl’
 class QUrl;
       ^
In file included from /usr/include/qt4/QtCore/qobject.h:50:0,
                 from /usr/include/qt4/QtGui/qlayout.h:45,
                 from /usr/include/qt4/QtGui/qboxlayout.h:45,
                 from /usr/include/qt4/QtGui/QVBoxLayout:1,
                 from tab.h:44,
                 from tab.cpp:41:
/usr/include/qt4/QtCore/qlist.h:418:17: error: invalid use of incomplete type ‘class QUrl’
                 (reinterpret_cast<T*>(current))->~T();
                 ^
In file included from /usr/include/qt4/QtCore/qvariant.h:48:0,
                 from /usr/include/qt4/QtCore/qsettings.h:46,
                 from /usr/include/qt4/QtCore/QSettings:1,
                 from tab.h:46,
                 from tab.cpp:41:
/usr/include/qt4/QtCore/qmetatype.h:299:7: error: forward declaration of ‘class QUrl’
 class QUrl;
       ^
Makefile:494: recipe for target 'tab.o' failed
make: *** [tab.o] Error 1

**Comment by Dman95** [comment]
Thank you for report. I have fixed the problem. Please check it now.

**Comment by MikeyG** [comment]
That fixed it, thanks.
