### ISSUE TITLE
Падение программы в режиме отладки при показе регистров Linux

### ISSUE THREAD

**Issue by unixwz** [Dman95/SASM#49]
Программа падает в режиме отладки при попытки посмотреть регистры, при этом пробовал запускать из консоли, никаких ошибок не показывает.

Debian 8.3 Testing

**Comment by Dman95** [comment]
Пожалуйста, предоставьте код, при отладке которого программа падает.

**Comment by unixwz** [comment]
`format ELF

section '.text' executable
public main
main:
    ;write your code here
    xor eax, eax
    ret`
p.s использую FASM. Также пробовал на ноутбуке тоже под Debian, всё ок. Может быть у меня какая либо либа не стоит.

**Comment by unixwz** [comment]
`# -*- coding: utf-8 -*-
"""
Модуль для работы с Yandex.Music при помощи неофициального API
Автор: Дмитрий Буряков (unixwz.github.io)

Возможности модуля:
1) Search(keyword, search_type, offset)
    Поиск по ключевому слову с заданным типом и смещением страниц.
    - keyword - ключевое слово
    - search_type - тип контента
        - tracks - треки
        - albums - альбомы
        - artists - исполнитель
    - offset - смещение (в страницах)
        к примеру offset=1 вернёт результаты расположенные на 1 странице,
        offset=2 вернёт результаты расположенные на 2 странице,
        при этом следует учитывать, что нумерация начинается с нуля.

TODO:
- получение прямой ссылки на аудио
"""

import httplib2
import json
import math


class YandexMusic(object):
    def __init__(self):
        self.base_url = "https://music.yandex.ru/handlers/"
        self.api_url = "https://music.yandex.ru/api/v2.0/handlers/"
        self.headers = {"Host": "music.yandex.ru",
                        "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0",
                        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
                        "Accept-Language": "ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3",
                        "Accept-Encoding": "gzip, deflate, br",
                        "Cookie": open("cookie.txt").read(),  # файл с куками
                        "Connection": "keep-alive",
                        "Cache-Control": "max-age=0"}

        self.key = "XGRlBW9FXlekgbPrRHuSiA"
        self.http = httplib2.Http(".cache")

    def search(self, keyword, search_type="tracks", offset=0):
        keyword = keyword.replace(" ", "+")
        # заменяем пробел "+", для HTTP запроса
        (resp, content) = self.http.request(
            self.base_url + "music-search.jsx?text=" + keyword + "&type=" + search_type + "&page=" + str(offset) + "",
            headers=self.headers)

        return json.loads(content)

    def get_page_count(self, keyword, search_type="tracks"):
        keyword = keyword.replace(" ", "+")
        # заменяем пробел "+", для HTTP запроса
        (resp, content) = self.http.request(
            self.base_url + "music-search.jsx?text=" + keyword + "&type=" + search_type + "", headers=self.headers)
        content = json.loads(content)
        page_count = int(math.ceil(float(content["pager"]["total"]) / 100))
        # определяем кол-во страниц на которые разбит найденный контент
        return page_count

    def get_track(self, track_id):
        (resp, content) = self.http.request(self.base_url + "track.jsx?track=" + str(track_id) + "&lang=ru",
                                            headers=self.headers)
        return json.loads(content)

    def get_artist(self, artist_id):
        (resp, content) = self.http.request(self.base_url + "artist.jsx?artist=" + str(artist_id) + "&lang=ru",
                                            headers=self.headers)
        return json.loads(content)

    def get_album(self):
        pass

    def get_download_link(self, track_id):
        track_info = self.__get_server_info__(track_id)
        print track_info

    def __get_server_info__(self, track_id):
        (info_resp, info_content) = self.http.request(self.api_url + "track/" + str(
            track_id) + ":129559/download/m?hq=0&external-domain=music.yandex.ru&forma=json", headers=self.headers)

        (download_resp, download_content) = self.http.request(json.loads(info_content)["src"], headers=self.headers)

        return download_content

    def get_lyrics(self):
        pass
`

**Comment by Dman95** [comment]
Скорее всего исправлено в SASM 3.8.0.
