### ISSUE TITLE
Переход на Qt5

### ISSUE THREAD

**Issue by proninyaroslav** [Dman95/SASM#50]
Здравствуйте. Так как Qt4 уже EOL, было бы логично перейти на Qt5, и, возможно, перейти на QML. Я с радостью мог бы вам помочь.

**Comment by ThomasThelen** [comment]
Привет жаль, но мой родной язык является английский . Это делается с помощью Google Translate . Я был в состоянии компиляции исходного кода с Qt 5.5.1 без каких-либо заметных ошибок . Это может быть хорошей идеей использовать QML до того, как проект становится слишком большим . В то же время я думаю , наклеивания с базовым Qt позволит большему количеству людей , чтобы помочь , чтобы они не должны учиться QML .

**Comment by Dman95** [comment]
Спасибо за отклик, однако здесь я согласен с @ThomasThelen по обоим вопросам.

Программа изначально разрабатывалась под Qt 5, поддержка Qt 4 была добавлена в целях совместимости. На сегодняшний день SASM успешно собирается под Qt 5 (в частности, с помощью Qt 5 выпускаются релизные сборки под Windows).

QML действительно стоит использовать только сразу при написании нового проекта. В данный момент значительных функциональных улучшений переход на QML не даст, а сил на переписывание такого достаточно большого кода может быть потрачено очень много.
