### ISSUE TITLE
watching values of variables for programs written in MASM

### ISSUE THREAD

**Issue by fadni** [Dman95/SASM#51]
First, thank you for this great software. I am trying to use your IDE for teaching Assembly language using MASM (because i am using Irvine's book).

The only problem i am facing is how to watch a variable. When adding a variable name under "variable or expression", I receive "wrong variable or address". However, it works perfectly when debugging under NASM.

I am using MASM32 and tried to add /Zi option but no luck. Is there a quick solution? Thank you again

**Comment by ThomasThelen** [comment]
I'll try and check it out. Are you on x32 or x64? Can you provide a code snippet?

**Comment by Dman95** [comment]
SASM uses GDB as debugger. MASM can't generate debugging symbols in appropriate to GDB format. So you can not watch variable in MASM assembled program by name, only by address. NASM supports generating debugging symbols in appropriate format. So you can watch variables by name in programs assembled using it.
