### ISSUE TITLE
8-bit and 16-bit registers

### ISSUE THREAD

**Issue by huhuhugo1** [Dman95/SASM#53]
I want to ask how I could see partial registers - that is 16-bit AX, BX, CX, DX and 8-bit AL, AH, BL, BH, ... etc. Thanks :)

**Comment by ThomasThelen** [comment]
I don't believe there is a window for them however, could could find them by hand. See the link below. This should be an added feature in the next version.
http://stackoverflow.com/questions/15191178/assembly-programming-memory-allocating-eax-vs-ax-ah-al

**Comment by Dman95** [comment]
You can view described registers using memory window (Ctrl+M) and typing register name prefixed with $ sign (for example, $al, $bx). Also, as ThomasThelen already mentioned in link, described registers only are parts of registers, which you can view in registers window (Ctrl+R).
