### ISSUE TITLE
Syntax Highlighting

### ISSUE THREAD

**Issue by ThomasThelen** [Dman95/SASM#54]
I found a small caveat regarding the syntax highlighting. It appears that SASM recognizes the yWord keyword however, fails to recognize the m in front. I tested this with other keywords and similar results occur.
This occurs in NASM and MASM - the other assemblers seem to be unaffected although I may not be using correct keywords.

![SyntaxHighlightingBug](https://cloud.githubusercontent.com/assets/9289652/14069552/896c7342-f450-11e5-8904-6b86f0a3b055.PNG)

If you have any ideas on how to fix this let me know and I'll get on it.

**Comment by Dman95** [comment]
It was just a small typo in the regexps. I have fixed it in the last commit.

**Comment by Dman95** [comment]
Thank you for report!
