### ISSUE TITLE
QScintilla

### ISSUE THREAD

**Issue by lurumdare** [Dman95/SASM#61]
Может добавить поддержку QScintilla?

https://ru.wikipedia.org/wiki/Scintilla
https://habrahabr.ru/post/144714/

**Comment by Dman95** [comment]
Возможно, в будущем.

**Comment by feb21** [comment]
@Dman95 какой неоднозначный ответ, однако

**Comment by Dman95** [comment]
@feb21 думаю, в настоящий момент, не очень рационально переписывать всю существующую систему, чтобы использовать данный компонент. Да и времени нет. Если у Вас есть время, силы и желание, можете попробовать - приму pull request.
