### ISSUE TITLE
Different program output when debugged and not debugged, also timing dependent.

### ISSUE THREAD

**Issue by loa-in-** [Dman95/SASM#62]
Hello!
My system: Windows 7 x64
Assembler: NASM 64, as it came with SASM
This is my program: http://pastebin.com/9BK9hKkm

This is after stepping through the program: (as expected)
![screen1](https://cloud.githubusercontent.com/assets/1793030/19499864/16159aa0-9599-11e6-8c35-c761f73cb3e5.png)

EDIT: (removed my messy description / replaced with demonstation on a GIF)
![bugreport](https://cloud.githubusercontent.com/assets/1793030/19500216/7389bfac-959b-11e6-8c51-8197ee471fbc.gif)

When I step into the program, and then click Continue while execution is inside the loop, it doesn't output the second part of the output (as with Run).
When I break just before PRINT_HEX or PRINT_STRING then Continue, it works as it should.

Welp, assembly is easy. Learning assembly in these circumstances is hard.

**Comment by loa-in-** [comment]
Also you have seen unseen before lag (wtf) and the Continue button not responding (another wtf)

**Comment by Dman95** [comment]
Your program prints zero characters on the standard output. Because of it SASM didn't show it.
But this semi-bug was fixed and now everything should be ok.

**Comment by loa-in-** [comment]
Oh, so PRINT_HEX and such print to stderr?

**Comment by Dman95** [comment]
@loa-in- No, it prints to the standard output. But when you printed using "PRINT_CHAR bl" and bl was 0, it printed 0 to the standard output. And after it SASM considered that the output is ended. But in the new version of SASM this error was fixed.
