### ISSUE TITLE
hi,can i help you translate SASM into Chinese?

### ISSUE THREAD

**Issue by ZetaoYang** [Dman95/SASM#63]

**Comment by Dman95** [comment]
Hello!

Yes. It will be great.

To translate SASM into Chinese you need perform the next few steps:
1) Download the archive with the source code of the program:
https://github.com/Dman95/SASM/archive/master.zip
2) Download the translator file: 
https://dl.dropboxusercontent.com/u/41235289/language_zh.ts
2) Put file language_zh.ts in "SASM-master" directory.
3) Download Qt Linguist using this link: 
https://github.com/thurask/Qt-Linguist/releases/download/20150629/linguist.exe
4) Open file language_zh.ts in Qt Linguist, translate all phrases in its interface and save the file.
5) Send this file to me. I'll add it in the near releases.

**Comment by ZetaoYang** [comment]
i got it. wait my good news.

**Comment by ZetaoYang** [comment]
@Dman95 I finished it just now.I have sent that file to you via your e-mail.

**Comment by Dman95** [comment]
@ZetaoYang Ok. I got it. I will add the translation in the new SASM release.

**Comment by ZetaoYang** [comment]
@Dman95  Well,it sounds great.

**Comment by Dman95** [comment]
I have added Chinese language in SASM.
