### ISSUE TITLE
hi,why not add deb package for ubuntu distribution.

### ISSUE THREAD

**Issue by ZetaoYang** [Dman95/SASM#64]
at present , i use [alien](https://sourceforge.net/projects/alien-pkg-convert/) to convert rpm to deb .

**Comment by ZetaoYang** [comment]
here is my advice, you can use [AppImage](http://appimage.org/) for linux distribution.

**Comment by Dman95** [comment]
There is such package. You can download it from OBS repository: http://download.opensuse.org/repositories/home:/Dman95/ Maybe you just haven't noticed it using previous site link. So I have replaced the link to the aforecited.

**Comment by probonopd** [comment]
@Dman95 it's not an AppImage that would run on most Linux distributions.

**Comment by Dman95** [comment]
@probonopd Yes, I know. But this thread speech is about the deb package for Ubuntu, which exists in that repository.

**Comment by ZetaoYang** [comment]
@Dman95 thank you.

**Comment by alexmyczko** [comment]
You're welcome: debian source package (also works for ubuntu): http://phd-sid.ethz.ch/debian/sasm/
