### ISSUE TITLE
Missing io.inc

### ISSUE THREAD

**Issue by Meresmata** [Dman95/SASM#65]
Hi,

  I compiled SASM from source last weekend I have so remarks and questions. In detail:

I got myself an old (2009) netbook (atom, i386) and installed Xubuntu 16.04 onto it. I downloaded SASM's source code from github and compiled it last weeked with some changes. That changes are: Not all mentioned dipendencies existed, also qmake did not work. Than with make and make install all was fine. After the installation I removed the folder...
Now when I open SASM and want to start to compile I got the following error messages:

/tmp/SASM/program.asm:1: fatal: unable to open include file `io.inc'
gcc: error: /tmp/SASM/program.o: Datei oder Verzeichnis nicht gefunden
gcc: error: /tmp/SASM/macro.o: Datei oder Verzeichnis nicht gefunden
gcc: fatal error: no input files
compilation terminated.

When I understand the problem, the only important part is, that io.inc is missing (why?). That's why I have to questions. Were do I get it, and where do I have to put it in?

With kind regards!

**Comment by loa-in-** [comment]
So you ignored the dependencies? What were you missing?

Also qmake install script would probably copy a set of shared include files, that aid in in SASM's usage with different assemblers, and that's clearly what you're missing. 
You will find them in the repo in "Linux/share/SASM/include/"

**Comment by Meresmata** [comment]
Hi,

 I checked which dependencies did not exist and that were/are libqt4-core  and libqt4-gui... 
With a quick search I found out, that the do not exist for ubuntu distros anymore.
 
An alternative would be, to uninstall (how?) and add the the repro (how?). Or I could try to compile a second time... (with a hint, what to do with the missing packages... etc. and qmake) but either way my connection this weekend is to slow to donload anything. ;(

**Comment by loa-in-** [comment]
Oh, OK, I see that they're dummy packages, so as long as you have qt4 stuff installed anyway (libqt4-designer,libqt4-opengl,libqt4-svg,libqtgui4,libqtwebkit4,libqt4-network) it will work.
I'm not up to date with Ubuntu it seems...

As to the include file 'io.inc': files you're looking for are in `Linux/share/sasm/include/` in this repository. Copying the *.inc files to the directory of your asm source should resolve compilation errors, but it probably should go to `/usr/share/sasm/include` or `/usr/local/share/sasm/include/`, depending on your distro.

**Comment by Meresmata** [comment]
Ok,

 I had got all those packages installed... 

Thanks, now I really know what the problem is: (The files are in place)

when I start sasm with the gui... and  want to compile I get the error message:

[21:25:49] Warning! Errors have occurred in the build:
/tmp/SASM/program.asm:1: fatal: unable to open include file `io.inc'
gcc: error: /tmp/SASM/program.o: Datei oder Verzeichnis nicht gefunden
gcc: error: /tmp/SASM/macro.o: Datei oder Verzeichnis nicht gefunden
gcc: fatal error: no input files
compilation terminated.

When I start sasm in the cli get the error, too. But starting with sudo sasm, the compilation is succesful. So it's a privilage problem. When I start thunar with gksudo thunar /usr/share/sasm/include/ and look at the privilages: Then I see that root is the owner (as expected), and others can only read the file io.inc. But that should be ok?

So what might cause the problem?

**Comment by loa-in-** [comment]
maybe others can't read the directory above include files.

**Comment by loa-in-** [comment]
To summarize this to SASM owner: qmake file should reference actual packages required to prevent these problems in future. If qmake ran well, the privilleges should have been set properly and this wouldn't occur.
