### ISSUE TITLE
no output in sasm

### ISSUE THREAD

**Issue by nana16992** [Dman95/SASM#67]
Hello, I am trying to run code of "Hello world", and print a string. The code is fine, was taken from the internet.
The output window remains empty, while the program compiles without any errors.
I am using Linux Ubuntu 16.04.
Please help me to understand whats the matter, thanks a lot!

**Comment by Dman95** [comment]
Hello,

Please provide the source code you want to compile and SASM version.

**Comment by mariusvn** [comment]
I have the same problem, my hello world works, i executed the executable (%temp%/SAMSprog.exe) in my terminal and it worked perferctly. the output frame in sams howerver, was empty
