### ISSUE TITLE
Unable to install on ubuntu 16.04 (Linux Mint 18.1) because of fasm

### ISSUE THREAD

**Issue by turbanoff** [Dman95/SASM#70]
```
$ sudo dpkg -i sasm_3.7.0_amd64.deb 
[sudo] пароль для gtf: 
(Чтение базы данных … на данный момент установлено 284982 файла и каталога.)
Подготовка к распаковке sasm_3.7.0_amd64.deb …
Распаковывается sasm (3.7.0) …
dpkg: ошибка при обработке архива sasm_3.7.0_amd64.deb (--install):
 попытка перезаписать «/usr/bin/fasm», который уже имеется в пакете fasm 1.71.51-1
При обработке следующих пакетов произошли ошибки:
 sasm_3.7.0_amd64.deb
```

Why sasm .deb package bundle `fasm` instead of depend on it?

**Comment by maestroprog** [comment]
У меня проблема решилась после удаления установленного пакета fasm
Fasm идет "в комплекте" вместе с SASM

**Comment by turbanoff** [comment]
Это да, помогло. Просто это не linux way. Если всё равно пользователи будут ставить deb, то зачем тянуть fasm с собой?

**Comment by Dman95** [comment]
Сейчас точно не помню - не могу сказать зачем это нужно (возможно для отладки), но там fasm не дефолтный, а собранный вручную с какими-то флагами. Так что пока так.
