### ISSUE TITLE
Working directory for compiler

### ISSUE THREAD

**Issue by turbanoff** [Dman95/SASM#71]
Я пытаюсь скомпилировать один ASM проект из IDE - http://websvn.kolibrios.org/listing.php?repname=Kolibri+OS&path=%2Fkernel%2Ftrunk%2F
Файл kernel.asm содержит fasm _инструкцию_ include.
include предполагает, что файл располагается по заданному пути относительно текущей директории.
Если запустить просто в командной строке `fasm kernel.asm` - всё скомпилируется хорошо. Но при запуске из IDE выставляется какой-то странный working directory.
Я думаю, текущая папка при запуске внешнего процесса должна совпадать с папкой, где находится файл. Или нужно дать возможно это сконфигурировать.

**Comment by Dman95** [comment]
В SASM 3.8.0 добавлена опция запуска ассемблера в текущей директории. Спасибо за сообщение!
