### ISSUE TITLE
start project error FASMHellox64.asm

### ISSUE THREAD

**Issue by catafest** [Dman95/SASM#81]
I start with base 64 your project and I got this error:
`Build log:
[19:01:53] Build started...
[19:01:53] Warning! Errors have occurred in the build:
error: write failed.
n 1.71.39  (1048576 kilobytes memory)`

**Comment by lberserq** [comment]
Please provide strace log

**Comment by catafest** [comment]
See the next image ... Is the default FASMHellox64.asm example of SASM 
<a href="http://imgur.com/tcleHbi"><img src="http://i.imgur.com/tcleHbi.png" title="source: imgur.com" /></a>

**Comment by Dman95** [comment]
You don't have write rights in the working directory. Choose another directory.
