### ISSUE TITLE
GCC Flags don't seem to work

### ISSUE THREAD

**Issue by LegendL3n** [Dman95/SASM#82]
I wanted to make a binary as small as possible so I added this flags:
`-Os -ffunction-sections -fdata-sections -fno-exceptions`
Now the Linking options is as follows:
`$PROGRAM.OBJ$ $MACRO.OBJ$ -g -Os -ffunction-sections -fdata-sections -fno-exceptions -o $PROGRAM$ -m32`
But for some reason(even after restarting) it gives me the same ~50kb binary.
Is this a bug or am I doing something wrong?

**Comment by lberserq** [comment]
-fno-exception is useless, because macro obj is a compiled c file. I think a lot of size is occupied by generated debuginfo. Also you cannot reduce size at all because compilation options for macro file  have hardcoded here https://github.com/Dman95/SASM/blob/master/mainwindow.cpp#L903

**Comment by Dman95** [comment]
If you want small binary size, you shouldn't use macro library and disable debug info. For the most common usage it's normal situation.
