### ISSUE TITLE
`_start' is defined many times

### ISSUE THREAD

**Issue by easonjim** [Dman95/SASM#84]
![image](https://user-images.githubusercontent.com/5625433/28495020-d84a17aa-6f72-11e7-9222-7a13ab8871d5.png)

**Comment by lberserq** [comment]
change your linker to ld, and your linker settings to $PROGRAM.OBJ$ -g -o $PROGRAM$ -m elf_i386 for i386 binary.

**Comment by easonjim** [comment]
@lberserq Thank you very much.
It works.My configuration is as follows:
![image](https://user-images.githubusercontent.com/5625433/28633042-00a83296-7265-11e7-8065-64ea6533ec61.png)
I also have another solution that uses the -e parameter to specify the entry:
`$PROGRAM.OBJ$ $MACRO.OBJ$ -g -o $PROGRAM$ -m32 -e _start -nostartfiles`
![image](https://user-images.githubusercontent.com/5625433/28633118-55aa87d0-7265-11e7-80f5-d599fe6293c9.png)
