### ISSUE TITLE
Offset from registers in Memory tab inconsistent?

### ISSUE THREAD

**Issue by PeterUlb** [Dman95/SASM#86]
Assuming I want to see the value on address $esp+20 in the memory tab. Currently, I need to manually add  the offset to the eax address to display it correctly. When I use $esp+20 it results in the same address I calculated manually, but the value is just off.

![1](https://user-images.githubusercontent.com/13261215/29485902-f5ece116-84da-11e7-9698-c00aaed9a88e.PNG)
![2](https://user-images.githubusercontent.com/13261215/29485903-f6083588-84da-11e7-9e54-23064b9538fe.PNG)

13 is the value I expect. It would be great if $esp+X or -X would also work since that would save the time of manually calculating with hex values

**Comment by Dman95** [comment]
Thank you for reporting! Issue has been fixed and will be available in 3.9.0 version.
