### ISSUE TITLE
Removing gcc-multilib requirement for building from sources on linux

### ISSUE THREAD

**Issue by GregoryIstratov** [Dman95/SASM#88]
Hey! I wish to try your program, but I don't want to replace my gcc with gcc-multilib ( I'm on arch linux )
I'm not going to compile any 32 bit code with your IDE, I just don't need all these 32 bit libs on my system which will be pulled as dependencies if I install gcc-multilib.
So is it possible to remove multilib dependency for pure x86-64 architecture?
Thanks.

**Comment by Dman95** [comment]
Hello!
No, SASM is primarily developed for studying purposes. In many university courses it is needed to compile 32 bit assembly code. The easiest way to achieve such ability this is to add such dependency.
