### ISSUE TITLE
Debug doesn't works on NASM in Windows x64

### ISSUE THREAD

**Issue by DebugBSD** [Dman95/SASM#93]
When I try to debug an application I get the next error: 

An error has occurred in the debugger. Please check the names of the sections.

And I don't know where the problem is it. If I run the source code on Windows I don't have any problem. I just change the name of sections and the program works without any problem.

**Comment by ximir** [comment]
Здравствуйте.
Меня  сейчас  нет  на  месте, вы  можете 
самостоятельно скачать инструкцию с яндекс диска пройдя по этой ссылке:https://yadi.sk/i/it0o5qDepoarm

**Comment by DerNoobikeks** [comment]
There we go again.

**Comment by rainbowjose** [comment]
​

**Comment by Dman95** [comment]
Hello!
Please provide the code you want to compile and assembly and linking options.
