### ISSUE TITLE
about x86 opcode

### ISSUE THREAD

**Issue by wellorange** [Dman95/SASM#98]
If the interface can display opcode, it would be fine.
example; 26 c7 84 c8 44 33 22 11 78 56 34 12

**Comment by EthanMeep** [comment]
What are you guys making?

**Comment by SinghSimranjeet** [comment]
How do you stop getting this notification? I have muted the thread and yet still getting the notification.

**Comment by rdudejr** [comment]
You can checkout any time you like, but you can never leave.

**Comment by qminnich** [comment]
yea lmao, how do i make it stahp

**Comment by wellorange** [comment]
。。。
what happened?

**Comment by EthanMeep** [comment]
It’s a glitch in github. Contact support.

**Comment by piper4hire** [comment]
Has anyone seen any good movies lately?

-S

**Comment by Dman95** [comment]
Hello! 
I would be glad to accept such pull request :)
