### ISSUE TITLE
What plane to Qt5?

### ISSUE THREAD

**Issue by SergeyDjam** [Dman95/SASM#99]
Есть ли планы по переводу программы на Qt5?

**Comment by jverive** [comment]
Son of a ——-!

On Jul 11, 2018, at 2:38 PM, SergeyDjam <notifications@github.com<mailto:notifications@github.com>> wrote:


Есть ли планы по переводу программы на Qt5?

**Comment by SergeyDjam** [comment]
запрос можно закрывать.

**Comment by Dman95** [comment]
Здравствуйте!
Код полностью совместим с Qt 5. Более того бинарники под Windows, которые можно скачать, собираются с помощью Qt 5.2.1.
